### ISSUE TITLE
Feature: User Can Add a Run (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add previous run information, including run title, description, date, length, distance, and pace. (NOT GPS DATA)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to choose a custom run name and describe their run. They can also enter relevant run data.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add A Run 1](https://user-images.githubusercontent.com/105157437/200687003-55b880cc-8f65-4d35-92ed-2186e899cbfd.png)
![Add A Run 2](https://user-images.githubusercontent.com/105157437/200687008-6379269c-ec64-457b-a101-aaa5bd87f9f9.png)
![Add A Run 3](https://user-images.githubusercontent.com/105157437/200687010-d493c05b-d3dc-46fd-9ad8-82a8241ac665.png)

![Desktop_ Add Run 3](https://user-images.githubusercontent.com/105157437/200687083-c04db74e-dcc1-49c7-8c43-fdcbf9dc2fce.png)
![Desktop_ Add Run 2](https://user-images.githubusercontent.com/105157437/200687092-dc4af81e-6767-46a6-ac9d-d272cfca4379.png)
![Desktop_ Add Run 1](https://user-images.githubusercontent.com/105157437/200687097-7e440c35-70f4-44b5-a9e3-1e894286a9ee.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` with some dummy date for a run and add it to the database.

### ☁️ Server Tasks

- [x] Add an authorization middleware to index.js to check if the user is authorized before serving them run information.
- [x] Add a route after the authorization middleware for adding runs -- `app.post` to `api/runs`.
  - [x] Test with HTTPie 
  - [x] Destructure the userId from req.user
  - [x] Destructure `title`, `description`, `date`, `length`, and `pace` from req.body
    - [x] If anything is missing, throw a client error
  - [x] Insert the data into the database via `sql` and `db.query`.
  - [x] If successful, send a response with the new run in it as json
  - [x] Catch all other errors
- [x] Test with HTTPie 

### ⚡ Client Tasks

- [x] Create a `run-form` component.
- [x] Setup state in the run-form component, all inputs need stored in state.
- [x] Add the `html` to `render` to match the wireframes for mobile and desktop views using `floating-input` and `colored-input` components
- [x] Setup `handleChange` and `handleSubmit` methods for the form.
  - [x] `handleChange` should update state when any of the inputs are changed
  - [x] `handleSubmit` sends a fetch request `api/runs` --> POST
    - [x] If not, they should be navigated to the home page where they can view all their runs
 
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
