### ISSUE TITLE
Feature: User Can View Their Profile

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their profile information on the profile page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on `My Profile` via the navbar will take the user to their profile page. Here, they can see the information they entered when they signed up for the website.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![My Page -- Profile 2](https://user-images.githubusercontent.com/105157437/200703705-2ef2221a-ec98-48bf-8e8b-c2c96fdc8abb.png)

![Desktop_ My Profile 1](https://user-images.githubusercontent.com/105157437/200703709-515c6c9d-72c7-4cdd-9332-af209c6c6120.png)
![Desktop_ My Profile 2](https://user-images.githubusercontent.com/105157437/200703715-13be0565-6fab-4a27-95a2-4f90b1fd4065.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a `GET` route for grabbing current account information from the profile page.
  - [x] The route needs to go after the authorization middleware.
  - [x] The route grabs email, name, and birthday, and profilePhoto from the database.
  - [x] The route should `fetch` on `componentDidMount`.

### ⚡ Client Tasks

- [x] Create a class component `profile-card` to visualize user profile data.
- [x] `Fetch` data from above `GET` route on `componentDidMount` and store it in state -- we'll need it later for the edit feature.
- [x] After state has updated with the data, render the user's data to them on the page.
- [x] Don't worry about profile photo adding & removing OR edit functionality --> separate issues.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
