### ISSUE TITLE
Feature: User Can Create an Account (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register for an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the initial landing page, users can navigate to the registration page via the `sign up` link. On this page, they enter their account information and then click `create account` to create their account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Sign In 1](https://user-images.githubusercontent.com/105157437/200705518-abca5e87-ae91-4f4a-a33a-7de6f0c64e59.png)
![Sign In 2](https://user-images.githubusercontent.com/105157437/200705522-f35d89a0-86d3-40d3-bb10-bec74158cb18.png)
![Sign In 3](https://user-images.githubusercontent.com/105157437/200705526-0dfdb55d-1d1e-4ef8-9939-719ff5dd4379.png)

![Desktop_ Sign In 1](https://user-images.githubusercontent.com/105157437/200705582-dbc75671-4fdb-4d30-ba33-3d22fd7e2d4c.png)
![Desktop_ Sign In 2](https://user-images.githubusercontent.com/105157437/200705598-1e9bbd3a-dcbb-4db4-baa2-1b57ca202475.png)
![Desktop_ Sign In 3](https://user-images.githubusercontent.com/105157437/200705602-ca7f35ef-ff55-4183-882b-ef3954054844.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Download `schema.sql` file from dbdesigner and send to Scott for a check.
- [x] Add `schema.sql` to the database folder.
- [x] Add some dummy accounts to the `data.sql` file to use as practice for login / logout.
- [x] Create a new database in postgreSQL.
- [x] Import the `schema.sql` and `data.sql` into the new database.

### ☁️ Server Tasks

- [x] Code up a sign-up route for `server/index.js` -- `api/auth/sign-up` (api-authorization is good reference)
   - [x] Grab the username and password from req.body.
   - [x] If there is no username or password, throw an error.
     - [x] Set up an error handling middleware if one is not already set up to handle server-side errors.
   - [x] Hash the password using argon2.
   - [x] Insert the hashed password into the `users` table, returning the created userId, username, and createdAt.
   - [x] Catch any final errors.
   - [x] Test with HTTPie

### ⚡ Client Tasks

- [x] Get hash routing setup. (Use react-context as reference)
- [x] Create a navbar component to use for all desktop and mobile pages.
- [x] Create a sign-in component to use as a landing page. Don't worry about functionality yet! Just get the html in there.
- [x] Create a sign-up component with a form for the user to enter in all of their information. (auth-form.jsx from react-context is good reference!)
  - [x] State holds username and password
  - [x] Need functions for handling `input changes` and also `submit` (don't forget to bind `this`)
  - [x] `handleChange` uses event.target to grab the current value and stores it in state
  - [x] `handleSubmit` sends a fetch request to the `api/auth/sign-up` server route we just built with the user's username and password in the body.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
