### ISSUE TITLE
Feature: User Can Login to their Account (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Via the landing page, users can login to their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the landing page, users can enter the email and password they used to register their account to sign-in. This takes them to their `progress` page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Sign In 1 (1)](https://user-images.githubusercontent.com/105157437/200705854-4942a2fb-6b33-4082-b3a3-e3321abe5aac.png)
![My Page -- Progress (3)](https://user-images.githubusercontent.com/105157437/200705855-c4e7a3bb-8df3-478f-b5a2-cc7ba2e01a02.png)

![Desktop_ Sign In 1 (1)](https://user-images.githubusercontent.com/105157437/200705793-56ac47d3-c0af-44ad-9837-d28efa6526df.png)
![Desktop_ My Runs_ Progress Sq 2 (2)](https://user-images.githubusercontent.com/105157437/200705808-0bb10f4c-3291-408b-8b29-fd34ba979fad.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Code up a sign-up route for `server/index.js` -- `api/auth/sign-in` (api-authorization is good reference)
   - [x] Grab username and password from `req.body`
   - [x] Send an `sql query` looking for `userId` and `hashed password` where the entry matches sign-in information
   - [x] If we find a match, verify the hashed password against the user provided password using `argon2`
   - [x] If the password checks out, create a payload and sign a token with `jwt`
   - [x] Send a response with the token and the user (with payload)
 - [x] Catch any final errors.
 - [x] Test with HTTPie

### ⚡ Client Tasks

- [x] Update the `auth-form` component to ensure it can send requests to the `sign-in` route.
- [x] If `result.user` and `result.token` are returned from the fetch request (success), sign the user in.
  - [x] Add `user` and `isAuthorizing` to the App state.
  - [x] Add a `handleSignIn` method to the `App` component (bind `this`!)
    - [x] Grab the userId and the token from result
    - [x] Set the token into local storage & set the user into state
- [x] Add a `handleSignOut` method to the `App` component (bind `this`!)
  - [x] Remove the token from local storage
  - [x] Set user in state to null
- [x] In the `App` component, within `componentDidMount` check for a token in local storage
  - [x] If token is present, pull it and decode the token to get the user.
  - [x] Set this user into state and set `isAuthorizing` to false 
- [x] In the `App` component inside render...
  - [x] Check if `this.state.isAuthorizing` --> if it is, return null.
  - [x] Otherwise, destructure the user and route from state and pass into context.
  - [x] Also destructure `handleSignIn` and `handleSignOut` methods from `this` and pass into context.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
