### ISSUE TITLE
Feature: User Can View Their Runs (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all previous runs and associated run data.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After a user adds a run, they are redirected to the `activities` tab. This tab contains a list of all previous runs. When a run is clicked on, relevant information about that run is pulled up in a modal window. (No search-bar yet!!!!)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![My Page -- Activities (1)](https://user-images.githubusercontent.com/105157437/200687914-75b8159c-7456-4c2d-b7aa-9ad8a9c021b4.png)
![My Page -- Activites_Notes (3)](https://user-images.githubusercontent.com/105157437/200687922-763af7f7-256f-4924-be5c-ada2ee1cc36e.png)

![Desktop_ Activites 2](https://user-images.githubusercontent.com/105157437/200688017-9a05a0b7-d639-4a0f-ae65-c62eb1b37b13.png)
![Desktop_ Activites 3](https://user-images.githubusercontent.com/105157437/200688031-af28bbf8-b1b0-45d5-91e8-22cb7f113b66.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Add a few sample runs to `data.sql` to use for testing.

### ☁️ Server Tasks

- [x] Add a GET request route for `/api/runs` that grabs all of the runs from the runs table and returns them as an object to the client.
  - [x] This route should go AFTER authorization middleware -- we need the userId to know which user's runs to pull from the db.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a `secondary-navbar` component for mobile screens to navigate around the home page. Match the wireframes provided.
  - [x] Get all the HTML laid out in the component -- each 1/3 of the navbar should be a clickable `button`.
  - [x] `onClick`, switch the appropriate page that the user clicked on. Get all that hash routing set-up. Don't worry about page content yet.
- [x] Modify the `secondary-navbar` component for desktop screens. Match the wireframe.
  - [x] Add `props` for changing `flex-direction` from row to column.
  - [x] Add `props` for changing `background color` from light-blue to white.
- [x] Make the components for `progress`, `activities`, and `profile`. Keep 'em empty for now.
- [x] Set up hash routing for the `home` component from app for `progress`, `activities`, and `profile` hashes.
  - [x] Title message should change appropriately depending on which component will be rendered.
- [x] Triple check that all of the navigation is working from the navbar, homepage, and via a hash url.
- [x] Create a `view-run-mini-card` component that renders a mini-run card to match the wireframes.
- [x] Create a `view-run-main-card` component that renders a main-run card to match the wireframes.
- [x] `onClick` of a`view-run-mini-card`, pull up the `view-main-card` as a modal with that run information.
- [x] Within the `activities` component, add a fetch request to the GET `/api/runs` route and grab all of the runs.  
- [x] For each activity returned by the fetch request, create a `view-run-mini-card` and add it to the home page.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
