### ISSUE TITLE
Design Update: Tailwind Refactor

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#27]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User can create an account.

## 📐 Plan

> ##### Summary of the technical approach to be taken.

- [x] Refactor the navbar to use tailwind instead of mui components.
- [x] Refactor the login form and create an account form to use tailwind instead of mui components.
- [x] Remove mui from package.json and all files.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

Identical wireframes. For reference...
![Sign In 1 (2)](https://user-images.githubusercontent.com/105157437/201217610-b78cbefd-a66d-4e8f-adf6-d07a79913dd3.png)
![Sign In 2 (1)](https://user-images.githubusercontent.com/105157437/201217614-37190169-e8f1-43bd-b7b4-8b59bc1995bc.png)
![Desktop_ Sign In 1 (2)](https://user-images.githubusercontent.com/105157437/201217618-ff2764ca-0d5b-453a-a7fe-b28f2d42ca08.png)
![Desktop_ Sign In 2 (1)](https://user-images.githubusercontent.com/105157437/201217625-1ca210ba-5d91-4bd4-8d1b-9af7638ca22a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
