### ISSUE TITLE
Refactor:  In ProgressSquares, change auto-right-align from component-did-update to component-did-mount

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#34]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

Currently, in `progress-squares.jsx` the scroll function is in componentDidUpdate because when put in componentDidMount, the data has not arrived from `progress.jsx` so there is no data to scroll through. Because it only runs once, this scroll function needs moved to componentDidMount.

- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
