### ISSUE TITLE
Bug: Time-zone data is not accurate within the progress component

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#36]
#### Desired Behavior

> ##### The app should ...

Translate dates correctly on the clientside -- taking the uploading server-side date from UTC and transferring it to appropriate client-side timezone.

#### Actual Behavior

> ##### The app does this instead ...

All dates are stored as UTC, and are then passed back as UTC, creating inaccurate time data.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Be in a non-UTC time-zone and check the the progress tab. Squares will appear earlier or later than they are supposed to because of the inaccurate time zone problem.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Find and list all functions and components that use time-zone data from the database.
- [x] Ensure that all of the functions / components on the **client** side send and store data to the server in their time zone, but that the server accurately translates it to UTC.
- [x] Ensure that all of the functions / components on the **server** side respond to the client with the appropriate time zone data (this likely needs to be translated on the client-side!).
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
