### ISSUE TITLE
Feature: User Can Delete Previous Runs (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove previous runs and their associated data from the app permanently.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Within the same kebab menu as the edit functionality, a delete button allows the user to delete a run entry. Before deleting, a user must confirm their delete via a snack-bar that pops up at the bottom of the screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Delete Run 2](https://user-images.githubusercontent.com/105157437/200689475-686cea25-98fc-43ad-9e75-1df59019621a.png)
![Delete Run 3](https://user-images.githubusercontent.com/105157437/200689479-333e5f28-1e2d-4c0a-9cc7-1854702d7f23.png)
![Delete Run 4](https://user-images.githubusercontent.com/105157437/200689483-892b7472-6bd4-4444-a72e-400281fd2009.png)

![Desktop_ Delete Run 1](https://user-images.githubusercontent.com/105157437/200689584-b98c1f4c-b32b-40f6-8d79-d22719642d0c.png)
![Desktop_ Delete Run 2](https://user-images.githubusercontent.com/105157437/200689586-2dcebe09-7899-4928-9cad-67533a752f9b.png)
![Desktop_ Delete Run 3](https://user-images.githubusercontent.com/105157437/200689588-ae84c820-c48f-4328-96f3-a6f4cab12e35.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a delete route to `index.js` as `api/runs/:entryId` with the entryId parameter being the run entry to delete.
- [x] Test the route with HTTPie.
- [x] Respond to the client appropriately.

### ⚡ Client Tasks

- [x] Create a snackbar component similar to the wireframes. Make sure the snackbar is responsive with screen size.
- [x] Snackbar needs `isOpen` in its state to determine whether the snack is open or not.
- [x] Leave the deleting functionality on main card --> setup component so that when `delete` button is pressed on snackbar, it sends that confirmation up to the `main-run-card` to do the delete.
- [x] Ensure that after delete, the activities page is reloaded without the deleted run and that the deleted run is removed from the db.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
