### ISSUE TITLE
Feature: User Can View Their Progress Squares (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their run progress over the past year.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The progress screen shows a chart of squares similar to GitHub squares that shows users successful runs over the past year. On hover, the square shows the distance and date of that run. (No weekly run data or workouts YET!)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![My Page -- Progress (1)](https://user-images.githubusercontent.com/105157437/200690160-fbd9a1db-6cb8-432a-ba46-97459faa427e.png)
![My Page -- Progress_Hover (1)](https://user-images.githubusercontent.com/105157437/200690183-6d670b8f-2912-4c17-be22-2efc8825fb44.png)

![Desktop_ My Runs_ Progress Sq 1](https://user-images.githubusercontent.com/105157437/200690295-cb3daaa3-1e7b-4677-a656-14f99d77ef1f.png)
![Desktop_ My Runs_ Progress Sq 2](https://user-images.githubusercontent.com/105157437/200690298-f85adb2b-11f2-4048-aba2-db7127359ae1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` with data from a bunch of different days and months.

### ⚡ Server Tasks

- [x] Add a new get route to index.js that returns an array of objects with the last 365 days of run data in it. Each day should have a value of `run`, `no-run`, or `rest`. 
- [x] Test the route with HTTPie.
- [x] Respond to the client.

### ⚡ Client Tasks

- [x] Add a fetch request that grabs the 365 day run data and stores it in `state`
- [x] Add headings and monthly / yearly run data to progress component
- [x] Create a grid of squares from the last 365 days similar to the wireframe using `map`
- [x] Line up the days of the week and months on the grid x and y axis

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
