### ISSUE TITLE
Feature: User Can View Weekly Run Data (MVP)

### ISSUE THREAD

**Issue by cam-peck** [cam-peck/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their weekly run data via a line chart on the progress page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Beneath the running squares on the progress page is a line chart with weekly run data. On hover of a data point, the line chart shows the run date and distance -- similar to the data & distance shown on the squares chart on hover of square.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop_ My Runs_ Progress Sq 1 (1)](https://user-images.githubusercontent.com/105157437/200690910-944a2b16-6503-415b-9f3e-f1a3789db3b5.png)
![Desktop_ My Runs_ Progress Sq 2 (1)](https://user-images.githubusercontent.com/105157437/200690913-e0cf7d67-ca53-4dfa-9656-ce76186f7724.png)

![My Page -- Progress (2)](https://user-images.githubusercontent.com/105157437/200690958-e557c862-d6c6-45de-a9de-f8d7045a11c0.png)
![My Page -- Progress_Hover (2)](https://user-images.githubusercontent.com/105157437/200690961-03fed8e7-6e99-42df-bc74-b32fd33ae68a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` and make sure that there are runs for all previous weekdays this week

### ⚡ Client Tasks

- [x] Create a new component WeeklyRunChart in `weekly-run-chart.jsx`.
- [x] Rename `progressSquaresData` to something better and refactor the variable name in relevant files.
- [x] Pass down `progressData.squaresData` to WeeklyRunChart.
- [x] Once the data has arrived, create a line graph using `d3` to render the most recent week of data.
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
